name: lobe-chat-database-dev
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres-dev
    ports:
      - '5434:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        reservations:
          cpus: '2.0'
          memory: 1G
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio-dev
    ports:
      - '9002:9000'
      - '9003:9001'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
      - 'MINIO_DOMAIN=${S3_PUBLIC_DOMAIN}'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=${MINIO_API_CORS_ALLOW_ORIGIN}' # Your LobeChat's domain name.
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          cpus: '1.0'
          memory: 1G
    restart: always
    command: >
      server /etc/minio/data --address ":9002" --console-address ":9003"

  zitadel:
    image: ghcr.io/zitadel/zitadel:latest
    container_name: lobe-zitadel-dev
    ports:
      - 8082:8080
    volumes:
      - ./zitadel-config.yaml:/zitadel-config.yaml:ro
      - ./zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - ZITADEL_TLS_ALLOWED_ORIGINS=https://vi-4.ngrok.io,http://localhost:8082
    deploy:
      resources:
        reservations:
          cpus: '1.0'
          memory: 1G
    restart: always
    command: start-from-init --config /zitadel-config.yaml --steps /zitadel-init-steps.yaml --masterkey "cft3Tekr/rQBOqwoQSCPoncA9BHbn7QJ" --tlsMode external #MasterkeyNeedsToHave32Characters

  lobe:
    # image: lobehub/lobe-chat-database
    container_name: lobe-chat-dev
    ports:
      - '3211:3210'
    depends_on:
      - postgresql
      - minio
      - zitadel
    build:
      context: ./
      dockerfile: ./Dockerfile.database
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          cpus: '2.0'
          memory: 3G
    restart: always

  server:
    container_name: python-api-server-dev
    ports:
      - '3401:3400'
    build:
      context: ./plugins/project-vi
      dockerfile: ./Dockerfile
    volumes:
      - ./plugins/project-vi:/app
    deploy:
      resources:
        reservations:
          cpus: '2.0'
          memory: 3G
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local
